### PR TITLE
Fix certificate chains

### LINKED ISSUE #132: Certificate Chain Validation
## Expected behavior
Providing the full certificate chain (root and intermediate) via `--certfile ca.crt` mqtt should be able to verify the validity of the server certificate.

## Actual behavior
Mqtt outputs `unable to find valid certification path to requested target` even though openssl thinks it's valid:

`openssl verify -CAfile ca.crt mosquitto-server.crt`

### Steps
1. Configure Mosquitto with a Letsencrypt certificate created by issuer "=Digital Signature Trust Co., CN=DST Root CA X3"
2. Store the Letsencrypt CA and Root CA in a file ca.crt, `cat root.crt server.crt > ca.crt` - the order does not matter, I tried both
3. Run `mqtt pub -h FQDN -p 8883 -u USER -pw PASS --cafile ca.crt -t TOPIC -m MSG`

## Details
```
$ mqtt --version
1.1.1
Picocli 4.0.4
JVM: 13 (Oracle Corporation OpenJDK 64-Bit Server VM 13+33)
OS: Mac OS X 10.14.6 x86_64
```

### LINKED ISSUE #192: Can't connect to AWS IoT Core broker
I'm attempting to connect to an AWS IoT Core endpoint before evaluating using HiveMQ as MQTT client library in an Android app.
The purpose is testing and learning from mqtt-cli source how to use TLS auth via self-signed certificates within the HiveMQ client library.

Both MQTT Explorer and MQTTX can connect, subscribe and publish successfully to the broker with the same configuration (at least in my understanding)

I am not sure if it is related to #149 

## Expected behavior
Being able to connect to AWS IoT Core MQTT broker with TLS and self-signed certificates.

## Actual behavior
For mqtt shell connect
```
password can't be null
Timeout while waiting for CONNACK
```

For mqtt test
```
Could not build SSL config - password can't be null
```

### Steps

```
mqtt shell
connect -V 3 --host xxxxxv12345789-ats.iot.eu-north-1.amazonaws.com --port 8883 --cafile AmazonRootCA1.pem --cert xxx-certificate.pem.crt --key xxx-private.pem.key
```

or
```
mqtt test -V 3 --host xxxxxv12345789-ats.iot.eu-north-1.amazonaws.com --port 8883 --cafile AmazonRootCA1.pem --cert xxx-certificate.pem.crt --key xxx-private.pem.key
```

## Details
- Affected MQTT CLI version(s): 4.5.1
- Used JVM version:JVM: 1.8.0_181 (Oracle Corporation Java HotSpot(TM) 64-Bit Server VM 25.181-b13)
- Operating System: macOS 10.14.6

### PR DESCRIPTION
**Pull request by gitseti**
**Motivation**
Fix #132 
Fix #192 

`--cert`, `--cafile`, `--capath`  now should work correctly when certificate chains are used

**TODO**
- [ ] Fix `Could not build SSL config - password can't be null` for Java 8

**Changes**
- `FileToCertificatesConverter` now returns all certificates from a file to correctly recognize certificates chains
- Refactor`ShellConnectCommand`, `PublishCommand` and `SubscribeCommand` to use `SslOptions`
- Fixed Log level in `PublishCommand` and `SubscribeCommand` to correctly recognize `-v` option

### CODE REVIEW

File: src/main/java/com/hivemq/cli/commands/AbstractCommonFlags.java [hunk 1]
```diff
@@ -73,38 +56,15 @@
...
+    @CommandLine.Mixin
+    private final SslOptions sslOptions = new SslOptions();
 
     @CommandLine.Option(names = {"-ws"}, description = "Use WebSocket transport protocol (default: false)", order = 2)
     private boolean useWebSocket;
 
     @CommandLine.Option(names = {"-ws:path"}, description = "The path of the WebSocket", order = 2)
-    @Nullable private String webSocketPath;
+    @Nullable
+    private String webSocketPath;
```
Comment (YannickWeber) [inline src/main/java/com/hivemq/cli/commands/AbstractCommonFlags.java:67]:
```suggestion
    private @Nullable String webSocketPath;
```

File: src/main/java/com/hivemq/cli/commands/AbstractCommonFlags.java [hunk 2]
```diff
@@ -119,149 +79,22 @@ public void setDefaultOptions() {
             try {
                 password = defaultCLIProperties.getPassword();
             } catch (Exception e) {
```
Comment (YannickWeber) [inline src/main/java/com/hivemq/cli/commands/AbstractCommonFlags.java:81]:
```suggestion
            } catch (final Exception e) {
```

File: src/main/java/com/hivemq/cli/commands/cli/PublishCommand.java [hunk 3]
```diff
@@ -112,11 +112,16 @@ public void run() {
...
         if (isDebug()) logLevel = "debug";
-        else if (isVerbose()) logLevel = "trace";
+        if (isVerbose()) logLevel = "trace";
         LoggerUtils.setupConsoleLogging(logToLogfile, logLevel);
 
         setDefaultOptions();
-        sslConfig = buildSslConfig();
+        try {
+            sslConfig = buildSslConfig();
+        } catch (Exception e) {
```
Comment (YannickWeber) [inline src/main/java/com/hivemq/cli/commands/cli/PublishCommand.java:121]:
```suggestion
        } catch (final Exception e) {
```

File: src/main/java/com/hivemq/cli/commands/cli/SubscribeCommand.java [hunk 4]
```diff
@@ -111,11 +111,16 @@ public void run() {
...
         if (isDebug()) logLevel = "debug";
-        else if (isVerbose()) logLevel = "trace";
+        if (isVerbose()) logLevel = "trace";
         LoggerUtils.setupConsoleLogging(logToLogfile, logLevel);
 
         setDefaultOptions();
-        sslConfig = buildSslConfig();
+        try {
+            sslConfig = buildSslConfig();
+        } catch (Exception e) {
```
Comment (YannickWeber) [inline src/main/java/com/hivemq/cli/commands/cli/SubscribeCommand.java:120]:
```suggestion
        } catch (final Exception e) {
```

File: src/main/java/com/hivemq/cli/commands/options/SslOptions.java [hunk 5]
```diff
@@ -122,6 +127,38 @@ private boolean useBuiltSslConfig() {
                 .build();
     }
 
+    private void setDefaultOptions() {
+        final DefaultCLIProperties defaultCLIProperties = MqttCLIMain.MQTTCLI.defaultCLIProperties();
+
+        if (clientCertificateChain == null) {
+            try {
+                clientCertificateChain = defaultCLIProperties.getClientCertificateChain();
+            } catch (Exception e) {
```
Comment (YannickWeber) [inline src/main/java/com/hivemq/cli/commands/options/SslOptions.java:136]:
```suggestion
            } catch (final Exception e) {
```

File: src/main/java/com/hivemq/cli/commands/options/SslOptions.java [hunk 6]
```diff
@@ -122,6 +127,38 @@ private boolean useBuiltSslConfig() {
...
+                Logger.error(e,"Default client certificate chain could not be loaded ({})", Throwables.getRootCause(e).getMessage());
+            }
+        }
+
+        if (clientPrivateKey == null) {
+            try {
+                clientPrivateKey = defaultCLIProperties.getClientPrivateKey();
+            } catch (Exception e) {
```
Comment (YannickWeber) [inline src/main/java/com/hivemq/cli/commands/options/SslOptions.java:144]:
```suggestion
            } catch (final Exception e) {
```

File: src/main/java/com/hivemq/cli/commands/options/SslOptions.java [hunk 7]
```diff
@@ -122,6 +127,38 @@ private boolean useBuiltSslConfig() {
...
+
+        try {
+            final Collection<X509Certificate> defaultServerCertificate = defaultCLIProperties.getServerCertificateChain();
+            if (defaultServerCertificate != null) {
+                if(serverCertificateChain == null){
+                    serverCertificateChain = new ArrayList<>();
+                }
+                serverCertificateChain.addAll(defaultServerCertificate);
+            }
+        } catch (Exception e) {
```
Comment (YannickWeber) [inline src/main/java/com/hivemq/cli/commands/options/SslOptions.java:157]:
```suggestion
        } catch (final Exception e) {
```

File: src/main/java/com/hivemq/cli/commands/shell/ShellConnectCommand.java [hunk 8]
```diff
@@ -68,9 +68,17 @@ public ShellConnectCommand(@NotNull final MqttClientExecutor mqttClientExecutor)
 
     public void run() {
         setDefaultOptions();
-        sslConfig = buildSslConfig();
+
+        try {
+            sslConfig = buildSslConfig();
+        } catch (Exception e) {
```
Comment (YannickWeber) [inline src/main/java/com/hivemq/cli/commands/shell/ShellConnectCommand.java:74]:
```suggestion
        } catch (final Exception e) {
```

File: src/main/java/com/hivemq/cli/converters/DirectoryToCertificatesConverter.java [hunk 9]
```diff
@@ -26,12 +26,13 @@
...
 import java.util.Collection;
 
-public class DirectoryToCertificateCollectionConverter implements CommandLine.ITypeConverter<Collection<X509Certificate>> {
+public class DirectoryToCertificatesConverter implements CommandLine.ITypeConverter<Collection<X509Certificate>> {
     static final String DIRECTORY_NOT_FOUND = "The given directory was not found.";
     static final String NOT_A_DIRECTORY = "The given path is not a valid directory";
     static final String NO_CERTIFICATES_FOUND_IN_DIRECTORY = "The given directory does not contain any valid certificates";
 
     @Override
+    @NotNull
```
Comment (YannickWeber) [inline src/main/java/com/hivemq/cli/converters/DirectoryToCertificatesConverter.java:35]: inline @NotNull

File: src/main/java/com/hivemq/cli/converters/FileToCertificatesConverter.java [hunk 10]
```diff
@@ -21,15 +21,18 @@
...
 
-public class FileToCertificateConverter implements CommandLine.ITypeConverter<X509Certificate> {
+public class FileToCertificatesConverter implements CommandLine.ITypeConverter<Collection<? extends Certificate>> {
 
     static final String NO_VALID_FILE_EXTENSION = "The given file does not conform to a valid Certificate File Extension as " + Arrays.toString(CertificateConverterUtils.FILE_EXTENSIONS);
 
     @Override
-    public X509Certificate convert(final @NotNull String s) throws Exception {
+    @NotNull
+    public Collection<X509Certificate> convert(final @NotNull String s) throws Exception {
```
Comment (YannickWeber) [inline src/main/java/com/hivemq/cli/converters/FileToCertificatesConverter.java:35]: inline @NotNull

File: src/main/java/com/hivemq/cli/utils/CertificateConverterUtils.java [hunk 11]
```diff
@@ -21,18 +21,29 @@
...
 import java.security.cert.X509Certificate;
+import java.util.Collection;
 
 public class CertificateConverterUtils {
     public static final String[] FILE_EXTENSIONS = {".pem", ".cer", ".crt"};
     public static final String NO_VALID_CERTIFICATE = "The given file contains no valid or supported certficate,";
 
-    public static X509Certificate generateX509Certificate(final @NotNull File keyFile) throws Exception {
+    @NotNull
+    public static Collection<X509Certificate> generateX509Certificates(final @NotNull File keyFile) throws Exception {
```
Comment (YannickWeber) [inline src/main/java/com/hivemq/cli/utils/CertificateConverterUtils.java:35]:
```suggestion
    public static @NotNull Collection<X509Certificate> generateX509Certificates(final @NotNull File keyFile) throws Exception {
```

**Review by YannickWeber — APPROVED** [review]
